name: CreateUsers

on: [push]

jobs:
  create-users:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible and SSHPASS
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "185.2.102.70," \
            -u root \
            -e "ansible_password=03011bfQDZWAPz8g9" \
            -e "ansible_ssh_pass=03011bfQDZWAPz8g9" \
            -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no'" \
            playbook.yml