name: CreateUsers

on: [push]

jobs:
  create-users:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i "185.2.102.70," \
            -u root \
            -e "ansible_password=${{ secrets.PROD_SRV_PASSWORD }}" \
            -e "ansible_ssh_pass=${{ secrets.PROD_SRV_PASSWORD }}" \
            playbook.yml